version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # This is a "volume exclusion." By specifying a path that already exists within a bind mount, you're essentially
      # telling Docker to exclude this directory from the bind-mount and let the container handle it on its own
      # filesystem. This improves performance by avoiding the I/O synchronization overhead for this directory.
      - /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    depends_on:
      - db

  caddy:
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  db:
    build:
      context: .
      target: app_db
    environment:
      # TODO - Change password to use secret
      - MSSQL_SA_PASSWORD=Pass@word123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###
    
volumes:
  db_data:

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
