version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  db:
    build:
      context: .
      target: app_db
    environment:
      # TODO - Change password to use secret
      - MSSQL_SA_PASSWORD=Pass@word123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
    
volumes:
  db_data:

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
